<?php

namespace AppBundle\Repository;
use Symfony\Bridge\Doctrine\RegistryInterface;
/**
 * ActeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActeurRepository extends \Doctrine\ORM\EntityRepository
{

    /*
    public function findBySomething($value)
    {
        return $this->createQueryBuilder('a')
            ->where('a.something = :value')->setParameter('value', $value)
            ->orderBy('a.id', 'ASC')
            ->setMaxResults(10)
            ->getQuery()
            ->getResult()
        ;
    }
    */
}
