<?php

namespace AppBundle\Repository;
use Symfony\Bridge\Doctrine\RegistryInterface;
/**
 * PersonnageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonnageRepository extends \Doctrine\ORM\EntityRepository
{



    public function findByActeur($id)
    {
        $qb = $this->createQueryBuilder('a');

        $qb
            ->where('a.acteur = :id')
            ->setParameter('id', $id)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

}